#ifndef _SDL_KEYBOARD_H_
#define _SDL_KEYBOARD_H_

#include <SDL3/SDL_keycode.h>

#define HOST_KEY_BACKSPACE SDLK_BACKSPACE
#define HOST_KEY_LSHIFT SDLK_LSHIFT
#define HOST_KEY_RSHIFT SDLK_RSHIFT
#define HOST_KEY_SPACE SDLK_SPACE
#define HOST_KEY_RETURN SDLK_RETURN
#define HOST_KEY_0 SDLK_0
#define HOST_KEY_EXCLAIM SDLK_EXCLAIM
#define HOST_KEY_1 SDLK_1
#define HOST_KEY_2 SDLK_2
#define HOST_KEY_3 SDLK_3
#define HOST_KEY_4 SDLK_4
#define HOST_KEY_LEFT SDLK_LEFT
#define HOST_KEY_5 SDLK_5
#define HOST_KEY_DOWN SDLK_DOWN
#define HOST_KEY_6 SDLK_6
#define HOST_KEY_UP SDLK_UP
#define HOST_KEY_7 SDLK_7
#define HOST_KEY_RIGHT SDLK_RIGHT
#define HOST_KEY_8 SDLK_8
#define HOST_KEY_9 SDLK_9
#define HOST_KEY_A SDLK_A
#define HOST_KEY_B SDLK_B
#define HOST_KEY_C SDLK_C
#define HOST_KEY_D SDLK_D
#define HOST_KEY_E SDLK_E
#define HOST_KEY_F SDLK_F
#define HOST_KEY_G SDLK_G
#define HOST_KEY_H SDLK_H
#define HOST_KEY_I SDLK_I
#define HOST_KEY_MINUS SDLK_MINUS
#define HOST_KEY_J SDLK_J
#define HOST_KEY_EQUALS SDLK_EQUALS
#define HOST_KEY_K SDLK_K
#define HOST_KEY_L SDLK_L
#define HOST_KEY_PERIOD SDLK_PERIOD
#define HOST_KEY_M SDLK_M
#define HOST_KEY_COMMA SDLK_COMMA
#define HOST_KEY_N SDLK_N
#define HOST_KEY_O SDLK_O
#define HOST_KEY_APOSTROPHE SDLK_APOSTROPHE
#define HOST_KEY_P SDLK_P
#define HOST_KEY_Q SDLK_Q
#define HOST_KEY_R SDLK_R
#define HOST_KEY_S SDLK_S
#define HOST_KEY_T SDLK_T
#define HOST_KEY_U SDLK_U
#define HOST_KEY_SLASH SDLK_SLASH
#define HOST_KEY_V SDLK_V
#define HOST_KEY_W SDLK_W
#define HOST_KEY_X SDLK_X
#define HOST_KEY_LEFTBRACKET SDLK_LEFTBRACKET
#define HOST_KEY_RIGHTBRACKET SDLK_RIGHTBRACKET
#define HOST_KEY_Y SDLK_Y
#define HOST_KEY_SEMICOLON SDLK_SEMICOLON
#define HOST_KEY_Z SDLK_Z


#define HOST_KEY_MOD_RSHIFT SDL_KMOD_RSHIFT
#define HOST_KEY_MOD_LSHIFT SDL_KMOD_LSHIFT
#define HOST_KEY_MOD_CAPS SDL_KMOD_CAPS

#endif