#ifndef _SDL_KEYBOARD_H_
#define _SDL_KEYBOARD_H_

#include "platform.h"
#include <SDL3/SDL.h>

#define HOST_KEY_LCONTROL SDL_SCANCODE_LCTRL
#define HOST_KEY_RCONTROL SDL_SCANCODE_RCTRL
#define HOST_KEY_SPACE SDL_SCANCODE_SPACE
#define HOST_KEY_RETURN SDL_SCANCODE_RETURN
#define HOST_KEY_0 SDL_SCANCODE_0
#define HOST_KEY_1 SDL_SCANCODE_1
#define HOST_KEY_2 SDL_SCANCODE_2
#define HOST_KEY_3 SDL_SCANCODE_3
#define HOST_KEY_4 SDL_SCANCODE_4
#define HOST_KEY_5 SDL_SCANCODE_5
#define HOST_KEY_6 SDL_SCANCODE_6
#define HOST_KEY_7 SDL_SCANCODE_7
#define HOST_KEY_8 SDL_SCANCODE_8
#define HOST_KEY_9 SDL_SCANCODE_9
#define HOST_KEY_0 SDL_SCANCODE_0
#define HOST_KEY_Q SDL_SCANCODE_Q
#define HOST_KEY_W SDL_SCANCODE_W
#define HOST_KEY_E SDL_SCANCODE_E
#define HOST_KEY_R SDL_SCANCODE_R
#define HOST_KEY_T SDL_SCANCODE_T
#define HOST_KEY_Y SDL_SCANCODE_Y
#define HOST_KEY_U SDL_SCANCODE_U
#define HOST_KEY_I SDL_SCANCODE_I
#define HOST_KEY_O SDL_SCANCODE_O
#define HOST_KEY_P SDL_SCANCODE_P
#define HOST_KEY_A SDL_SCANCODE_A
#define HOST_KEY_S SDL_SCANCODE_S
#define HOST_KEY_D SDL_SCANCODE_D
#define HOST_KEY_F SDL_SCANCODE_F
#define HOST_KEY_G SDL_SCANCODE_G
#define HOST_KEY_H SDL_SCANCODE_H
#define HOST_KEY_J SDL_SCANCODE_J
#define HOST_KEY_K SDL_SCANCODE_K
#define HOST_KEY_L SDL_SCANCODE_L
#define HOST_KEY_Z SDL_SCANCODE_Z
#define HOST_KEY_X SDL_SCANCODE_X
#define HOST_KEY_C SDL_SCANCODE_C
#define HOST_KEY_V SDL_SCANCODE_V
#define HOST_KEY_B SDL_SCANCODE_B
#define HOST_KEY_N SDL_SCANCODE_N
#define HOST_KEY_M SDL_SCANCODE_M

#define HOST_KEY_BACKSPACE SDL_SCANCODE_BACKSPACE
#define HOST_KEY_MINUS SDL_SCANCODE_MINUS
#define HOST_KEY_EQUALS SDL_SCANCODE_EQUALS
#define HOST_KEY_LEFTBRACKET SDL_SCANCODE_LEFTBRACKET
#define HOST_KEY_RIGHTBRACKET SDL_SCANCODE_RIGHTBRACKET
#define HOST_KEY_SEMICOLON SDL_SCANCODE_SEMICOLON
#define HOST_KEY_COMMA SDL_SCANCODE_COMMA
#define HOST_KEY_PERIOD SDL_SCANCODE_PERIOD
#define HOST_KEY_SLASH SDL_SCANCODE_SLASH
#define HOST_KEY_BACKSLASH SDL_SCANCODE_BACKSLASH
#define HOST_KEY_SINGLE_QUOTE SDL_SCANCODE_APOSTROPHE
#define HOST_KEY_GRAVE SDL_SCANCODE_GRAVE
#define HOST_KEY_LEFT SDL_SCANCODE_LEFT
#define HOST_KEY_RIGHT SDL_SCANCODE_RIGHT
#define HOST_KEY_UP SDL_SCANCODE_UP
#define HOST_KEY_DOWN SDL_SCANCODE_DOWN

#define HOST_KEY_CMD_1 SDL_SCANCODE_F1
#define HOST_KEY_CMD_2 SDL_SCANCODE_F2
#define HOST_KEY_CMD_3 SDL_SCANCODE_F3
#define HOST_KEY_CMD_4 SDL_SCANCODE_F4
#define HOST_KEY_CMD_5 SDL_SCANCODE_F5

inline const bool* keyboard_get_state(int* numKeys = nullptr) {
	return SDL_GetKeyboardState(numKeys);
}

inline void keyboard_reset() {
	SDL_ResetKeyboard();
}
#endif